import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  // --- UTTAR PRADESH ---
  {
    id: 'up-1',
    title: 'The Taj View Homestay',
    description: 'Wake up to the mesmerizing view of the Taj Mahal. This boutique homestay offers a rooftop cafe and authentic Mughlai cuisine.',
    type: 'Private room',
    category: 'City',
    location: 'Agra, Uttar Pradesh',
    pricePerNight: 45,
    rating: 4.92,
    reviewCount: 320,
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Taj Mahal View', 'Wifi', 'Rooftop Cafe', 'Breakfast'],
    hostName: 'Rahul',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'up-2',
    title: 'Heritage Haveli on the Ghats',
    description: 'Experience the spiritual energy of Varanasi in this restored 18th-century Haveli right on the banks of the Ganges.',
    type: 'Entire home',
    category: 'City',
    location: 'Varanasi, Uttar Pradesh',
    pricePerNight: 85,
    rating: 4.88,
    reviewCount: 150,
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Ganga View', 'Yoga Deck', 'Vegetarian Meals', 'Boat Ride'],
    hostName: 'Anjali',
    coordinates: { lat: 25.3176, lng: 82.9739 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 }
  },
  {
    id: 'up-3',
    title: 'Nawabi Palace Suite',
    description: 'Live like royalty in the City of Nawabs. This heritage suite features antique furniture and sprawling gardens.',
    type: 'Private suite',
    category: 'Castles',
    location: 'Lucknow, Uttar Pradesh',
    pricePerNight: 120,
    rating: 4.95,
    reviewCount: 89,
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Pool', 'Butler Service', 'Garden', 'Wifi'],
    hostName: 'Aditya',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'up-4',
    title: 'Spiritual Retreat Cottage',
    description: 'A peaceful cottage in the heart of Vrindavan. Perfect for meditation and exploring the ancient temples.',
    type: 'Entire cottage',
    category: 'City',
    location: 'Vrindavan, Uttar Pradesh',
    pricePerNight: 35,
    rating: 4.75,
    reviewCount: 210,
    // Fixed: Replaced the invalid website link with a beautiful verified image of Prem Mandir/Temple architecture
    imageUrl: 'https://plus.unsplash.com/premium_photo-1697729637789-3f1ef7c623c0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    amenities: ['Garden', 'AC', 'Temple Access', 'Kitchen'],
    hostName: 'Meera',
    coordinates: { lat: 27.5706, lng: 77.6593 },
    capacity: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 }
  },

  // --- MAHARASHTRA ---
  {
    id: 'mh-1',
    title: 'Sea Facing Penthouse',
    description: 'Luxury penthouse overlooking the Arabian Sea. Located in Bandra West, close to top cafes and nightlife.',
    type: 'Entire apartment',
    category: 'City',
    location: 'Mumbai, Maharashtra',
    pricePerNight: 150,
    rating: 4.85,
    reviewCount: 412,
    imageUrl: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Sea View', 'Gym', 'Wifi', 'Elevator'],
    hostName: 'Rohan',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 }
  },
  {
    id: 'mh-2',
    title: 'Misty Hill Villa with Pool',
    description: 'Escape the city chaos in this private villa in Lonavala. Features a private pool and lush green surroundings.',
    type: 'Entire villa',
    category: 'Amazing pools',
    location: 'Lonavala, Maharashtra',
    pricePerNight: 200,
    rating: 4.91,
    reviewCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Private Pool', 'BBQ Grill', 'Mountain View', 'Parking'],
    hostName: 'Sameer',
    coordinates: { lat: 18.7515, lng: 73.4077 },
    capacity: { guests: 8, bedrooms: 4, beds: 4, bathrooms: 4 }
  },
  {
    id: 'mh-3',
    title: 'Vineyard Farmhouse Stay',
    description: 'Stay in the wine capital of India. Enjoy wine tasting tours and sunset views over the vineyards.',
    type: 'Farm stay',
    category: 'Camping',
    location: 'Nashik, Maharashtra',
    pricePerNight: 90,
    rating: 4.78,
    reviewCount: 95,
    imageUrl: 'https://images.unsplash.com/photo-1516246843873-9d12356b6fab?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Vineyard Tour', 'Breakfast', 'Patio', 'AC'],
    hostName: 'Priya',
    coordinates: { lat: 19.9975, lng: 73.7898 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 }
  },
  {
    id: 'mh-4',
    title: 'Konkan Beach Hut',
    description: 'Rustic bamboo huts right on the white sands of Tarkarli. Fresh seafood and water sports available.',
    type: 'Hut',
    category: 'Beachfront',
    location: 'Malvan, Maharashtra',
    pricePerNight: 40,
    rating: 4.80,
    reviewCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Beach Access', 'Restaurant', 'Scuba Diving', 'Hammock'],
    hostName: 'Ganesh',
    coordinates: { lat: 16.0526, lng: 73.4659 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },

  // --- RAJASTHAN ---
  {
    id: 'rj-1',
    title: 'The Pink City Heritage',
    description: 'A 200-year-old heritage home in the heart of Jaipur. Traditional decor with modern comforts.',
    type: 'Private room',
    category: 'Castles',
    location: 'Jaipur, Rajasthan',
    pricePerNight: 75,
    rating: 4.96,
    reviewCount: 500,
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Courtyard', 'Rooftop', 'Wifi', 'Breakfast'],
    hostName: 'Vikram',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'rj-2',
    title: 'Lake Pichola Palace View',
    description: 'Stunning views of the Lake Palace and Jag Mandir. Enjoy a romantic dinner on the terrace.',
    type: 'Entire home',
    category: 'Amazing pools',
    location: 'Udaipur, Rajasthan',
    pricePerNight: 180,
    rating: 4.98,
    reviewCount: 230,
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Lake View', 'Pool', 'Fine Dining', 'Spa'],
    hostName: 'Karan',
    coordinates: { lat: 24.5854, lng: 73.7125 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'rj-3',
    title: 'Golden Sands Desert Camp',
    description: 'Luxury swiss tents in the Sam Sand Dunes. Cultural folk dance and camel safari included.',
    type: 'Tent',
    category: 'Desert',
    location: 'Jaisalmer, Rajasthan',
    pricePerNight: 100,
    rating: 4.89,
    reviewCount: 340,
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Camel Safari', 'Dinner', 'Bonfire', 'Attached Bath'],
    hostName: 'Hameed',
    coordinates: { lat: 26.9157, lng: 70.9083 },
    capacity: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 }
  },
  {
    id: 'rj-4',
    title: 'Blue City Boutique Stay',
    description: 'Located in the winding streets of the old city, with a direct view of the Mehrangarh Fort.',
    type: 'Private room',
    category: 'City',
    location: 'Jodhpur, Rajasthan',
    pricePerNight: 55,
    rating: 4.85,
    reviewCount: 180,
    // Updated to a highly reliable Blue City view
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661904165347-369200d4bf72?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    amenities: ['Fort View', 'Cafe', 'Wifi', 'Guide'],
    hostName: 'Sanjay',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },

  // --- GOA ---
  {
    id: 'ga-1',
    title: 'Portuguese Villa with Pool',
    description: 'A restored Portuguese-style villa in North Goa. Close to Baga and Calangute beaches.',
    type: 'Entire villa',
    category: 'Amazing pools',
    location: 'Calangute, Goa',
    pricePerNight: 250,
    rating: 4.90,
    reviewCount: 110,
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Pool', 'Garden', 'Caretaker', 'Wifi'],
    hostName: 'Rosie',
    coordinates: { lat: 15.5494, lng: 73.7558 },
    capacity: { guests: 10, bedrooms: 5, beds: 6, bathrooms: 5 }
  },
  {
    id: 'ga-2',
    title: 'Sunset Beach Shack',
    description: 'Wooden cottage right on Palolem Beach. Fall asleep to the sound of waves.',
    type: 'Hut',
    category: 'Beachfront',
    location: 'Palolem, Goa',
    pricePerNight: 60,
    rating: 4.82,
    reviewCount: 250,
    imageUrl: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Sea View', 'Bar', 'Hammock', 'Wifi'],
    hostName: 'Pedro',
    coordinates: { lat: 15.0100, lng: 74.0200 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'ga-3',
    title: 'Latin Quarter Apartment',
    description: 'Charming apartment in Fontainhas, the Latin Quarter of Panjim. Colorful streets and art galleries nearby.',
    type: 'Entire apartment',
    category: 'City',
    location: 'Panjim, Goa',
    pricePerNight: 70,
    rating: 4.75,
    reviewCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    amenities: ['AC', 'Kitchen', 'Balcony', 'Wifi'],
    hostName: 'Maria',
    coordinates: { lat: 15.4909, lng: 73.8278 },
    capacity: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 }
  },
  {
    id: 'ga-4',
    title: 'Agonda Serenity Cottage',
    description: 'Quiet and peaceful cottage in South Goa. Ideal for couples looking for privacy.',
    type: 'Cottage',
    category: 'Beachfront',
    location: 'Agonda, Goa',
    pricePerNight: 50,
    rating: 4.88,
    reviewCount: 130,
    imageUrl: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Garden', 'Beach Access', 'AC', 'Breakfast'],
    hostName: 'Sunil',
    coordinates: { lat: 15.0440, lng: 73.9877 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },

  // --- KERALA ---
  {
    id: 'kl-1',
    title: 'Munnar Tea Garden Treehouse',
    description: 'Stay amidst lush green tea plantations in a luxury treehouse. Breathtaking views of the misty hills.',
    type: 'Treehouse',
    category: 'Treehouses',
    location: 'Munnar, Kerala',
    pricePerNight: 110,
    rating: 4.95,
    reviewCount: 200,
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Mountain View', 'Breakfast', 'Trekking', 'Balcony'],
    hostName: 'Jose',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'kl-2',
    title: 'Luxury Backwater Houseboat',
    description: 'Cruise through the famous backwaters of Alleppey. All meals included, prepared by an onboard chef.',
    type: 'Houseboat',
    category: 'Beachfront',
    location: 'Alleppey, Kerala',
    pricePerNight: 160,
    rating: 4.90,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=1200&auto=format&fit=crop',
    amenities: ['AC Room', 'Chef', 'Upper Deck', 'Canoe Ride'],
    hostName: 'Vinu',
    coordinates: { lat: 9.4981, lng: 76.3388 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 }
  },
  {
    id: 'kl-3',
    title: 'Cliffside Resort Varkala',
    description: 'Perched on the red cliffs of Varkala overlooking the Arabian Sea. Steps away from the beach.',
    type: 'Private room',
    category: 'Beachfront',
    location: 'Varkala, Kerala',
    pricePerNight: 65,
    rating: 4.82,
    reviewCount: 140,
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Sea View', 'Ayurvedic Spa', 'Yoga', 'Restaurant'],
    hostName: 'Deepa',
    coordinates: { lat: 8.7379, lng: 76.7163 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'kl-4',
    title: 'Rainforest Wayanad Stay',
    description: 'Eco-friendly stay deep inside the Wayanad rainforests. Spot wildlife and enjoy the sounds of nature.',
    type: 'Cabin',
    category: 'Camping',
    location: 'Wayanad, Kerala',
    pricePerNight: 80,
    rating: 4.86,
    reviewCount: 95,
    // Updated to a reliable forest/cabin image
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Nature Walk', 'Bonfire', 'Organic Food', 'Parking'],
    hostName: 'Thomas',
    coordinates: { lat: 11.6854, lng: 76.1320 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 }
  },
  
  // --- HIMACHAL PRADESH ---
  {
    id: 'hp-1',
    title: 'Snow View Cabin Manali',
    description: 'Cozy wooden cabin with heating, offering panoramic views of snow-capped peaks.',
    type: 'Entire cabin',
    category: 'Cabins',
    location: 'Manali, Himachal Pradesh',
    pricePerNight: 70,
    rating: 4.88,
    reviewCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Heater', 'Kitchen', 'Mountain View', 'Wifi'],
    hostName: 'Amit',
    coordinates: { lat: 32.2432, lng: 77.1892 },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 }
  },
  {
    id: 'hp-2',
    title: 'Colonial Bungalow Shimla',
    description: 'Heritage stay from the British era. Walking distance to the Mall Road and Ridge.',
    type: 'Entire home',
    category: 'City',
    location: 'Shimla, Himachal Pradesh',
    pricePerNight: 110,
    rating: 4.80,
    reviewCount: 160,
    imageUrl: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Fireplace', 'Garden', 'Cook', 'Parking'],
    hostName: 'Col. Singh',
    coordinates: { lat: 31.1048, lng: 77.1734 },
    capacity: { guests: 6, bedrooms: 3, beds: 3, bathrooms: 3 }
  },
  {
    id: 'hp-3',
    title: 'River Camps Kasol',
    description: 'Camping by the Parvati river. Enjoy trance music, bonfires, and stargazing.',
    type: 'Tent',
    category: 'Camping',
    location: 'Kasol, Himachal Pradesh',
    pricePerNight: 30,
    rating: 4.70,
    reviewCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?q=80&w=1200&auto=format&fit=crop',
    amenities: ['River View', 'Bonfire', 'Music', 'Meals'],
    hostName: 'Bunty',
    coordinates: { lat: 32.0100, lng: 77.3150 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  },
  {
    id: 'hp-4',
    title: 'Dharamshala Yoga Retreat',
    description: 'Stay near the Dalai Lama Temple. Daily yoga sessions and organic sattvic food provided.',
    type: 'Private room',
    category: 'City',
    location: 'Dharamshala, Himachal Pradesh',
    pricePerNight: 55,
    rating: 4.92,
    reviewCount: 90,
    // Updated to a reliable mountain/monastery image
    imageUrl: 'https://images.unsplash.com/photo-1576487248805-cf45f6bcc67f?q=80&w=1200&auto=format&fit=crop',
    amenities: ['Yoga Hall', 'Mountain View', 'Wifi', 'Library'],
    hostName: 'Tenzin',
    coordinates: { lat: 32.2190, lng: 76.3239 },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 }
  }
];